export let noteData = {
    lastId: 7,
    note:[
    {
        name: 1,
        id: 1,
        createDate: 'April 20, 2021',
        category: 'Task',
        content: 'Tomate, bread',
        contentDate: '2021',
        isArchive: false,
    },
    {
        name: 2,
        id: 2,
        createDate: 'April 20, 2021',
        category: 'Task',
        content: 'Tomate, bread',
        contentDate: '2021',
        isArchive: false,
    },
    {
        name: 3,
        id: 3,
        createDate: 'April 20, 2021',
        category: 'Task',
        content: 'Tomate, bread',
        contentDate: '2021',
        isArchive: false,
    },
    {
        name: 4,
        id: 4,
        createDate: 'April 20, 2021',
        category: 'Task',
        content: 'Tomate, bread',
        contentDate: '2021',
        isArchive: true,
    },
    {
        name: 5,
        id: 5,
        createDate: 'April 20, 2021',
        category: 'Task',
        content: 'Tomate, bread',
        contentDate: '2021',
        isArchive: false,
    },
    {
        name: 6,
        id: 6,
        createDate: 'April 20, 2021',
        category: 'Task',
        content: 'Tomate, bread',
        contentDate: '2021',
        isArchive: true,
    },
    {
        name: 7,
        id: 7,
        createDate: 'April 20, 2021',
        category: 'Task',
        content: 'Tomate, bread',
        contentDate: '2021',
        isArchive: false,
    },
]};

// export default noteData;